apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: traffictargets.access.smi-spec.io
spec:
  group: access.smi-spec.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:                
                replicas:
                  type: integer
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    kind: TrafficTarget
    shortNames: 
      - tt
    plural: traffictargets
    singular: traffictarget 
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system-smi-conformance
  labels:
    istio-injection: enabled